baseURL = "/"
title = "GhostESP Documentation"
theme = "ghostesp"
defaultContentLanguage = "en"
canonifyURLs = false
enableRobotsTXT = true

[params]
  subtitle = ""

[params.versioning]
  default = "latest"

[[params.versioning.options]]
  id = "latest"
  name = "Latest"

[[params.versioning.options]]
  id = "v1.9.9"
  name = "v1.9.9"

[[params.versioning.options]]
  id = "v1.9.8"
  name = "v1.9.8"

[[params.versioning.options]]
  id = "v1.9.3"
  name = "v1.9.3"

[[params.versioning.options]]
  id = "v1.9"
  name = "v1.9"

[[params.versioning.options]]
  id = "v1.8.1"
  name = "v1.8.1"


[[params.versioning.options]]
  id = "v1.8"
  name = "v1.8"


[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
  page = ["HTML"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "github-dark"


